"""
Agent 4: Test Execution Agent
---------------------------------------
Runs the test files generated by Agent 3 and produces a structured report.json.

  - pytest  : always attempted (already installed in this env)
  - Playwright: attempted if npx is available, skipped gracefully if not

Usage:
    python run_tests.py
"""

import json
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent.parent / "agent3_test_writer" / "output"
REPORT_FILE = Path(__file__).parent / "report.json"
TEST_REPO_CACHE = (
    Path(__file__).parent.parent
    / "agent3_test_writer"
    / "repo_cache"
    / "ltc_hackathon_cra_automation_tests"
)


# ---------------------------------------------------------------------------
# pytest runner
# ---------------------------------------------------------------------------
def run_pytest(test_file: Path) -> dict:
    if not test_file.exists():
        print(f"[agent4] pytest: file not found — {test_file}")
        return {"status": "skipped", "reason": str(test_file), "passed": 0, "failed": 0, "errors": 0}

    print(f"[agent4] Running pytest: {test_file.name}")
    result = subprocess.run(
        [sys.executable, "-m", "pytest", str(test_file), "-v", "--tb=short", "--no-header"],
        capture_output=True,
        text=True,
    )

    output = result.stdout + result.stderr
    for line in output.splitlines():
        print(f"  {line}")

    # Parse "5 passed, 2 failed, 1 error in 3.45s"
    m = re.search(r"(\d+) passed", output)
    passed = int(m.group(1)) if m else 0
    m = re.search(r"(\d+) failed", output)
    failed = int(m.group(1)) if m else 0
    m = re.search(r"(\d+) error", output)
    errors = int(m.group(1)) if m else 0

    return {
        "status": "passed" if result.returncode == 0 else "failed",
        "passed": passed,
        "failed": failed,
        "errors": errors,
        "output": output[:6000],
    }


# ---------------------------------------------------------------------------
# Playwright runner (optional)
# ---------------------------------------------------------------------------
def run_playwright(spec_file: Path) -> dict:
    if not spec_file.exists():
        print(f"[agent4] Playwright: file not found — {spec_file}")
        return {"status": "skipped", "reason": "spec file not found", "passed": 0, "failed": 0}

    try:
        subprocess.run(
            ["npx", "--version"], capture_output=True, check=True, timeout=10
        )
    except Exception:
        print("[agent4] Playwright: skipped (npx not available — install Node.js)")
        return {"status": "skipped", "reason": "npx not found", "passed": 0, "failed": 0}

    cwd = TEST_REPO_CACHE if TEST_REPO_CACHE.exists() else spec_file.parent
    print(f"[agent4] Running Playwright: {spec_file.name}")

    try:
        result = subprocess.run(
            ["npx", "playwright", "test", str(spec_file), "--reporter=line"],
            capture_output=True,
            text=True,
            cwd=str(cwd),
            timeout=180,
        )
    except subprocess.TimeoutExpired:
        return {"status": "error", "reason": "timed out after 180s", "passed": 0, "failed": 0}

    output = result.stdout + result.stderr
    for line in output.splitlines():
        print(f"  {line}")

    m = re.search(r"(\d+) passed", output)
    passed = int(m.group(1)) if m else 0
    m = re.search(r"(\d+) failed", output)
    failed = int(m.group(1)) if m else 0

    return {
        "status": "passed" if result.returncode == 0 else "failed",
        "passed": passed,
        "failed": failed,
        "output": output[:6000],
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> int:
    print("[agent4] Starting test execution")
    print(f"[agent4] Output dir: {OUTPUT_DIR}")

    pytest_results = run_pytest(OUTPUT_DIR / "test_generated.py")
    pw_results = run_playwright(OUTPUT_DIR / "test_generated.spec.js")

    total_passed = pytest_results.get("passed", 0) + pw_results.get("passed", 0)
    total_failed = pytest_results.get("failed", 0) + pw_results.get("failed", 0)

    report = {
        "timestamp": datetime.now().isoformat(),
        "pytest": pytest_results,
        "playwright": pw_results,
        "summary": {
            "total_passed": total_passed,
            "total_failed": total_failed,
            "overall": "passed" if total_failed == 0 and total_passed > 0 else "failed",
        },
    }

    REPORT_FILE.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(f"\n[agent4] Report saved → {REPORT_FILE}")
    print(f"[agent4] Result: {total_passed} passed  {total_failed} failed")

    return 0 if total_failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
